name: Download the Vertica RPM
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'When downloading with rpm from AWS s3, this is the AWS_ACCESS_KEY_ID for login purposes'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'When downloading with rpm from AWS s3, this is the AWS_SECRET_ACCESS_KEY for login purposes'
        required: true

# These permissions only apply when not running a PR.  GitHub actions makes PRs
# from forked repositories with extremely limited permissions that cannot be
# overwritten:
# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  packages: write
  security-events: write

env:
    # The script guess-server-upgrade-base-image.sh parses this URL. So,
    # if the structure of this URL ever changes be sure to verify if that
    # script needs an update.
    VERTICA_CE_URL: "https://vertica-community-edition-for-testing.s3.amazonaws.com/XCz9cp7m/vertica-25.1.0-0.RHEL8.x86_64.rpm"
    VERTICA_CE_URL_ARM64: "https://vertica-community-edition-for-testing.s3.amazonaws.com/XCz9cp7m/vertica-25.1.0-0.RHEL8.aarch64.rpm"

jobs:
  download-rpm:
    runs-on: ubuntu-latest
    steps:

    # Will download the RPM as prep for container building
    - name: Download Vertica RPM
      run: |
        s3Key=${{ secrets.AWS_ACCESS_KEY_ID }}
        s3Secret=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        date="$(date -u '+%a, %e %b %Y %H:%M:%S +0000')"

        for RPM_URL in ${{ env.VERTICA_CE_URL }} ${{ env.VERTICA_CE_URL_ARM64 }}
        do
            bucket=$(echo $RPM_URL | awk -F[/.] '{print $3}')
            arch=$(echo $RPM_URL | awk -F'.' '{print $(NF-1)}')
            file=$(echo $RPM_URL | awk -F'/' '{print $4"/"$5}')
            resource="/${bucket}/${file}"
            printf -v stringToSign "%s\n%s\n\n%s\n%b%s" "GET" "" "$date" "" "${resource}"
            signature="$(echo -n "$stringToSign" | openssl sha1 -hmac ${s3Secret} -binary | openssl base64)"
            curl -s -f -H "Date: ${date}" -H "Authorization: AWS ${s3Key}:${signature}" $RPM_URL -o docker-vertica/packages/vertica-latest.RHEL8.${arch}.rpm
        done

        cp docker-vertica/packages/*rpm docker-vertica-v2/packages
      shell: bash
